import { CurriculumSection } from '@/types/db';

export const CURRICULUM_SECTIONS: CurriculumSection[] = [
  {
    id: 'eindterm-1',
    eindtermNumber: 1,
    title: 'Administratie, documenten en apparatuur',
    titleEn: 'Administration, Documents and Equipment',
    titleAr: 'الإدارة، الوثائق والأجهزة الإلزامية',
    subtitle: 'BCT/CDT, chauffeurskaart, P-nummer, kentekenbewijs en APK-keuring',
    subtitleEn: 'BCT/CDT, driver card, P-number, vehicle registration and MOT inspection',
    subtitleAr: 'كمبيوتر التاكسي BCT، بطاقة السائق، رقم P، رخصة السيارة وفحص APK',
    icon: 'FileText',
    domain: 'bcdt',
    pageRange: 'p. 18 – 26',
    subsections: [
      {
        id: '1-1-bedrijfsvergunning',
        heading: 'P-nummer & Taxivergunning',
        headingEn: 'P-Number & Taxi Operating License',
        headingAr: 'رقم P ورخصة تشغيل التاكسي',
        content: 'Ieder taxibedrijf in Nederland heeft een personenvervoernummer (P-nummer). Dit is een uniek nummer waarmee de onderneming geregistreerd staat bij alle taxi-instanties, zoals Kiwa Register en de Inspectie Leefomgeving en Transport (ILT). Dit P-nummer staat geregistreerd in de BCT en op de taxi-informatiekaart.',
        contentEn: 'Every taxi company in the Netherlands holds a passenger transport number (P-number). This unique identifier is registered with all regulatory bodies including Kiwa Register and the Human Environment and Transport Inspectorate (ILT). It appears on the BCT and on the taxi information card.',
        contentAr: 'كل شركة تاكسي في هولندا تمتلك رقم نقل ركاب (P-nummer). وهو رقم تعريفي فريد مسجل لدى جميع الهيئات الرقابية بما فيها Kiwa ومفتشية النقل ILT، ويكون مسجلاً في جهاز BCT وبطاقة معلومات التاكسي.',
        keyPoints: [
          'P-nummer is het unieke registratienummer van de taxiondernemer.',
          'Vergunningbewijzen in papier waren vroeger verplicht, nu digitaal via Kiwa.',
          'Bij eenmanszaken en BV\'s moet het P-nummer altijd gekoppeld zijn aan het voertuig.',
        ],
        keyPointsEn: [
          'P-number is the unique registration number of the taxi carrier.',
          'Physical license certificates are largely replaced by digital Kiwa registration.',
          'The P-number must always be actively linked to the vehicle.',
        ],
        examTip: 'Op het CBR theorie-examen wordt gevraagd wat een P-nummer is: het unieke personenvervoernummer van de vervoerder/ondernemer, NIET van de chauffeur!',
        examTipEn: 'Exam trap: A P-number identifies the taxi company/carrier, NOT the individual driver!',
      },
      {
        id: '1-2-voertuigdocumenten',
        heading: 'Kentekencard, APK & Schadeformulier',
        headingEn: 'Vehicle Card, Annual MOT (APK) & Claim Form',
        headingAr: 'بطاقة رخصة المركبة، فحص APK السنوي ونموذج الحوادث',
        content: 'Elke taxi moet voorzien zijn van een geldige kentekencard en een jaarlijkse APK-keuring. Omdat taxi\'s aanzienlijk meer kilometers rijden dan particuliere auto\'s, moeten zij vanaf dag 1 (datum eerste toelating) ieder jaar opnieuw APK-gekeurd worden. Een Europees schadeformulier is wettelijk niet verplicht in Nederland, maar WEL verplicht voor bedrijven met het kwaliteitskeurmerk TX-Keur.',
        contentEn: 'Every taxi must carry a valid registration card and undergo an annual MOT (APK) inspection. Because taxis accumulate high mileage, they require APK every single year starting from day one. An accident claim form is legally optional in NL, but mandatory for companies certified with the TX-Keur quality mark.',
        contentAr: 'يجب أن تحمل كل سيارة تاكسي بطاقة تسجيل مركبة صالحة وفحص APK سنوي. نظراً للمسافات الطويلة، تخضع سيارات التاكسي لفحص APK كل عام بدءاً من اليوم الأول. نموذج الحوادث الأوروبي ليس إجبارياً بالقانون الهولندي، لكنه إلزامي للشركات الحاصلة على علامة الجودة TX-Keur.',
        keyPoints: [
          'APK keuring voor taxi\'s: Elk jaar verplicht (jaarlijks) vanaf eerste toelating.',
          'Kentekencard met chip moet bij controle direct getoond kunnen worden.',
          'Schadeformulier: Niet wettelijk verplicht in NL, wel verplicht bij TX-Keur keurmerk (en wettelijk verplicht in België).',
        ],
        keyPointsEn: [
          'MOT (APK) inspection for taxis: Mandatory EVERY year from initial road registration.',
          'Vehicle registration card with chip must be present in the vehicle.',
          'Claim form: Not legally mandatory in NL, but mandatory under TX-Keur quality standard.',
        ],
        examTip: 'CBR vraag: "Hoe vaak moet een nieuwe taxi APK worden gekeurd?" Antwoord: Ieder jaar (jaarlijks), vanaf het eerste jaar!',
        examTipEn: 'CBR question: "How often must a brand-new taxi receive an APK inspection?" Answer: Every year, right from the first year!',
      },
      {
        id: '1-3-bct-cdt',
        heading: 'Boordcomputer Taxi (BCT) & Toekomst CDT',
        headingEn: 'On-board Computer Taxi (BCT) & Future CDT',
        headingAr: 'كمبيوتر التاكسي BCT ومستقبل CDT الرقمي',
        content: 'De Boordcomputer Taxi (BCT) registreert arbeids- en rusttijden, ritgegevens en snelheden. De chauffeur logt in met de persoonlijke Chauffeurskaart en pincode. De pasfoto moet altijd zichtbaar blijven voor passagiers. Vanaf eind 2027 wordt de fysieke BCT geleidelijk vervangen door de Centrale Database Taxivervoer (CDT), waarbij data via apps en web-API\'s direct naar de overheid gestuurd wordt.',
        contentEn: 'The Taxi On-Board Computer (BCT) records working hours, rest breaks, ride details, and speeds. Drivers log in using their personal Driver Card and PIN code. The driver photo must remain visible to passengers at all times. By end of 2027, the hardware BCT transitions to the Central Taxi Database (CDT).',
        contentAr: 'يسجل كمبيوتر التاكسي (BCT) ساعات العمل والراحة، تفاصيل الرحلات والسرعة. يسجل السائق دخوله ببطاقته الشخصية ورقم PIN السري، ويجب أن تظل صورة السائق مرئية للركاب دائماً. بحلول نهاية 2027 يتم استبدال BCT بقاعدة بيانات مركزية رقمية CDT.',
        keyPoints: [
          'Inloggen vereist: Chauffeurskaart + 4-cijferige pincode.',
          'Pasfoto moet zichtbaar in het zicht van de passagier geplaatst zijn.',
          'Data bewaren: Chauffeurs moeten elke 5 weken hun chauffeurskaart ontladen/kopiëren naar de BCT.',
          'BCT is verzegeld door een erkend installateur; verbroken zegel = niet rijden!',
          'Uitloggen met nog geopende ritten is technisch onmogelijk.',
        ],
        keyPointsEn: [
          'Login requires: Driver card + 4-digit PIN code.',
          'Driver photo must be facing the passenger cabin.',
          'Data download: Driver card must be synced/discharged to BCT at least every 5 weeks.',
          'BCT is sealed by certified technicians; broken seal means the car cannot operate legally.',
          'Logging out while a trip is active is technically impossible.',
        ],
        examTip: 'Let op de 5-wekentermijn: gegevens van de chauffeurskaart moeten uiterlijk elke 5 weken worden overgezet!',
        examTipEn: 'Exam alert: Driver card data must be uploaded/backed up at least once every 5 weeks!',
      },
    ],
  },
  {
    id: 'eindterm-2',
    eindtermNumber: 2,
    title: 'Wet- en regelgeving',
    titleEn: 'Laws & Regulations',
    titleAr: 'القوانين واللوائح المنظمة',
    subtitle: 'Arbeidstijdenwet (ATW), Atb-v collectieve regeling, gordelplicht en verkeersregels',
    subtitleEn: 'Working Hours Act (ATW), Atb-v collective regime, seatbelts and traffic laws',
    subtitleAr: 'قانون ساعات العمل ATW، مرسوم النقل Atb-v، حزام الأمان وقوانين المرور',
    icon: 'Scale',
    domain: 'atbv',
    pageRange: 'p. 27 – 46',
    subsections: [
      {
        id: '2-1-arbeid-en-rusttijden',
        heading: 'Arbeids- en Rusttijden (Atb-v Collectieve Regeling)',
        headingEn: 'Work & Rest Hours (Atb-v Collective Agreement)',
        headingAr: 'ساعات العمل وفترات الراحة الإلزامية (الاتفاقية الجماعية)',
        content: 'Voor taxichauffeurs geldt het Arbeidstijdenbesluit Vervoer (Atb-v) onder de collectieve regeling (CAO Zorgvervoer en Taxi). De belangrijkste regels zijn: na maximaal 5,5 uur arbeid is een pauze van minimaal 15 minuten verplicht. De dagelijkse rust binnen een tijdvak van 24 uur is minimaal 10 uur (mag 2x per 14 dagen worden ingekort tot 8 uur). De wekelijkse rust is minimaal 72 uur per 14 dagen, op te delen in blokken van minstens 24 uur.',
        contentEn: 'Taxi drivers operate under the Transport Working Hours Decree (Atb-v) collective regime. Mandatory requirements: after at most 5.5 hours of work, a minimum 15-minute break is compulsory. Daily rest in any 24h window is minimum 10h (may be reduced twice per 14 days to 8h). Fortnightly rest is minimum 72h per 14x24h, in blocks of at least 24h.',
        contentAr: 'يخضع سائقو التاكسي لمرسوم ساعات عمل النقل (Atb-v) ضمن الاتفاقية الجماعية. القواعد الإلزامية: بعد 5.5 ساعات عمل كحد أقصى تجب استراحة 15 دقيقة على الأقل. الراحة اليومية خلال 24 ساعة لا تقل عن 10 ساعات (يمكن تقليصها مرتين كل 14 يوماً إلى 8 ساعات). الراحة النصف شهرية 72 ساعة مقسمة لكتل 24 ساعة على الأقل.',
        keyPoints: [
          'Pauze: Minimaal 15 minuten aaneengesloten na maximaal 5,5 uur arbeid.',
          'Een dienst mag NOOIT beginnen of eindigen met een pauze.',
          'Dagelijkse rust: Minimaal 10 uur per 24 uur (2x per 14 dagen mag 8 uur).',
          'Wekelijkse rust: Minimaal 72 uur per 14 dagen (in blokken van minimaal 24 uur).',
          'Gemiddelde arbeidstijd: Maximaal 48 uur per week berekend over een periode van 26 weken.',
          'Samenloopregeling: Bij 2 banen gelden altijd de strengste normen en moet je beide werkgevers informeren.',
        ],
        keyPointsEn: [
          'Break: Minimum 15 consecutive minutes after at most 5.5 hours of work.',
          'A shift may NEVER start or finish with a break.',
          'Daily rest: Minimum 10 hours per 24-hour cycle (twice per 14 days reducible to 8h).',
          'Fortnightly rest: Minimum 72 hours per 14 days (blocks of at least 24 consecutive hours).',
          'Average working hours: Maximum 48 hours per week averaged over 26 weeks.',
          'Dual employment: If holding 2 jobs, the most protective rules apply and both employers must be notified.',
        ],
        examTip: 'CBR examenfavoriet: "Mag een chauffeur beginnen met een pauze?" Antwoord: NEE, een dienst mag nooit met pauze starten of eindigen!',
        examTipEn: 'Frequent CBR trap: "Can a driver begin a shift with a break?" Answer: NO, shifts can never start or end with a break!',
      },
      {
        id: '2-2-gordelplicht',
        heading: 'Gordelplicht & Kinderzitjes (Art. 59 RVV)',
        headingEn: 'Seatbelt Rules & Child Restraints (Art. 59 RVV)',
        headingAr: 'قواعد حزام الأمان ومقاعد الأطفال (المادة 59)',
        content: 'In een taxi moet iedereen de veiligheidsgordel dragen. Passagiers van 12 jaar en ouder (of langer dan 1,35m) zijn zelfstandig aansprakelijk voor de boete. Voor kinderen jonger dan 12 jaar is de chauffeur verantwoordelijk. Uitzonderingen: Kinderen jonger dan 3 jaar mogen bij incidenteel taxivervoer zonder kinderzitje op de achterbank zitten (los, NOOIT voorin en NOOIT samen in 1 gordel). De chauffeur zelf heeft alleen vrijstelling tijdens stapvoets manoeuvreren op of direct bij de taxistandplaats.',
        contentEn: 'Every occupant in a taxi must wear a seatbelt. Passengers aged 12 and older are independently liable for fines. For children under 12, the driver bears legal responsibility. Children under 3 without a car seat may ride on the rear seat during incidental taxi transport (never in front, never sharing a belt). Drivers are only exempt when crawling on an official taxi rank.',
        contentAr: 'يلتزم جميع الركاب بربط حزام الأمان. الركاب من سن 12 عاماً فما فوق مسؤولون شخصياً عن الغرامة، بينما السائق مسؤول عن الأطفال دون 12 عاماً. استثناء: الأطفال دون 3 سنوات بدون مقعد خاص يسمح بنقلهم في المقعد الخلفي فقط في النقل العارض (ممنوع في الأمام وممنوع مشاركة حزام واحد). يُعفى السائق فقط أثناء المناورة البطيئة جداً في موقف التاكسي.',
        keyPoints: [
          'Vanaf 12 jaar: Passagier is zelf aansprakelijk voor de gordelboete.',
          'Onder 12 jaar: Taxichauffeur is verantwoordelijk.',
          'Kinderen < 3 jaar zonder kinderzitje: Alleen op de achterbank, NOOIT voorin!',
          'Twee personen in 1 gordel: Streng verboden.',
          'Chauffeursvrijstelling gordel: Uitsluitend bij stapvoets rijden op de officiële standplaats bij agressiegevaar.',
        ],
        keyPointsEn: [
          'Age 12+: Passenger is personally liable for their own seatbelt fine.',
          'Under 12: The taxi driver is legally responsible.',
          'Under 3 without child seat: Rear seat ONLY, NEVER front seat!',
          'Two people in one belt: Strictly prohibited.',
          'Driver exemption: Only when driving at walking pace on or immediately around an official taxi stand.',
        ],
        examTip: 'Let op: Klanten die zeggen "ik ben volwassen, u hoeft me niets te vertellen" krijgen zélf de boete als ze 12+ zijn. Maar onder de 12 betaalt de chauffeur!',
        examTipEn: 'Exam note: Passengers aged 12+ pay their own seatbelt fines. Under 12, the driver gets fined!',
      },
    ],
  },
  {
    id: 'eindterm-3',
    eindtermNumber: 3,
    title: 'Ritvoorbereiding',
    titleEn: 'Trip Preparation',
    titleAr: 'التحضير المسبق للرحلة والسيارة',
    subtitle: 'Bestelmarkt vs opstapmarkt, TTO standplaatsen, bandencontrole en ergonomie',
    subtitleEn: 'Pre-booked vs street hailing, TTO ranks, tyre inspections and vehicle setup',
    subtitleAr: 'السوق المحجوز مقابل سوق الشارع، مواقف TTO، فحص الإطارات وبيئة القيادة',
    icon: 'Compass',
    domain: 'transport',
    pageRange: 'p. 48 – 52',
    subsections: [
      {
        id: '3-1-marktvormen-tto',
        heading: 'Opstapmarkt vs Bestelmarkt & TTO',
        headingEn: 'Hailing Market vs Pre-booked & TTO Regulations',
        headingAr: 'سوق الشارع المباشر مقابل السوق المحجوز وقواعد TTO',
        content: 'De taximarkt is opgedeeld in twee categorieën: de opstapmarkt (standplaatsen en aanhouden op straat) en de bestelmarkt (contractvervoer, telefonische of app-boekingen zoals Uber of zorgvervoer). In steden met een TTO-beleid (Toegelaten Taxi Organisatie, zoals Amsterdam) mag een chauffeur alleen op openbare taxistandplaatsen staan als hij is aangesloten bij een erkende TTO en een daklicht van die TTO voert.',
        contentEn: 'The Dutch taxi sector consists of two markets: street hailing / ranks (opstapmarkt) and pre-booked rides (bestelmarkt, including healthcare transport and Uber apps). In municipalities with mandatory TTO policies (e.g., Amsterdam), drivers may only service taxi ranks if affiliated with an approved Authorized Taxi Organization (TTO) displaying its roof light.',
        contentAr: 'ينقسم سوق التاكسي الهولندي إلى قسمين: سوق الشارع المباشر والمواقف (Opstapmarkt) والسوق المحجوز مسبقاً (Bestelmarkt). في المدن التي تطبق نظام TTO مثل أمستردام، لا يُسمح بالوقوف في المواقف العامة إلا للسائقين المنتسبين لمنظمة TTO معتمدة ويحملون شارتها على سقف السيارة.',
        keyPoints: [
          'Opstapmarkt: Klant stapt in op standplaats of houdt taxi aan op straat. BCT en daklicht verplicht.',
          'Bestelmarkt: Vooraf besteld via centrale, app of contract. Geen daklicht verplicht als er geen opstapwerk is.',
          'TTO (Toegelaten Taxi Organisatie): Verplicht voor standplaatsen in o.a. Amsterdam.',
          'Rtx-vergunning: Gemeentelijke taxivergunning voor de standplaats.',
        ],
        keyPointsEn: [
          'Hailing market: Customer hails on street or boards at rank. Meter and roof light mandatory.',
          'Pre-booked market: Booked via dispatch/app/contract. No roof light required if purely pre-booked.',
          'TTO: Mandatory affiliation for servicing street ranks in cities like Amsterdam.',
          'Rtx permit: Municipal street taxi permit required for rank access.',
        ],
        examTip: 'Let op het verschil: Voor contractvervoer (zoals zorg of leerlingen) is GEEN daklicht nodig. Voor de openbare standplaats WEL!',
        examTipEn: 'Key exam difference: Contract / healthcare transport does NOT need a roof light, but street ranks DO!',
      },
      {
        id: '3-2-voertuigcontrole',
        heading: 'Banden, Lampjes & Stoelinstelling',
        headingEn: 'Tyres, Warning Lights & Ergonomic Adjustments',
        headingAr: 'فحص الإطارات، أضواء التحذير وتعديل المقاعد',
        content: 'Voor vertrek voert de chauffeur een visuele controle uit. Wettelijke minimale profieldiepte voor zomer- en winterbanden is 1,6 mm, maar het professionele advies voor taxi\'s is minimaal 2 mm (en 4 mm voor winterbanden). Bandenspanning wordt altijd "koud" gemeten (minstens 1 uur stilgestaan). Rood controlelampje betekent: direct veilig stoppen en motor uit; oranje controlelampje betekent: z.s.m. controleren/verhelpen maar je kunt voorzichtig naar een veilige plek rijden.',
        contentEn: 'Before departure, the driver performs a pre-trip inspection. Legal minimum tyre tread depth is 1.6 mm, but industry safety standard is 2.0 mm (4.0 mm for winter tyres). Tyre pressure must always be measured cold. A RED dash warning light requires an immediate safe stop; AMBER/ORANGE means check soon but safe to reach garage/parking.',
        contentAr: 'يقوم السائق بفحص شامل للمركبة قبل الانطلاق. الحد الأدنى القانوني لعمق مداس الإطار هو 1.6 ملم، بينما المعيار الاحترافي ينصح بـ 2 ملم على الأقل (و4 ملم للشتوي). يجب قياس ضغط الإطارات وهي باردة. الضوء الأحمر يعني التوقف الفوري الآمن، بينما البرتقالي يسمح بمواصلة القيادة بحذر لإصلاح العطل.',
        keyPoints: [
          'Minimale profieldiepte wettelijk: 1,6 mm over de gehele omtrek.',
          'Professioneel veiligheidsadvies: minimaal 2 mm (winterbanden: 4 mm).',
          'Bandenspanning meten: Alleen bij koude banden (na minimaal 1 uur stilstand).',
          'Rood lampje = Direct stoppen! Oranje lampje = Waarschuwing, z.s.m. naar garage.',
          'Kinderzitje achterwaarts voorin? Schakel ALTIJD de passagiersairbag uit!',
        ],
        keyPointsEn: [
          'Legal minimum tyre depth: 1.6 mm across the primary grooves.',
          'Safety recommendation: At least 2.0 mm (winter tyres: 4.0 mm).',
          'Tyre pressure check: Always when tyres are cold (after at least 1 hour resting).',
          'Red dashboard light = Stop immediately! Orange/amber = Warning, service soon.',
          'Rear-facing baby seat in front? ALWAYS deactivate the front passenger airbag!',
        ],
        examTip: 'Airbag-regel: Zet je een Maxi-Cosi tegen de rijrichting in op de voorstoel? De passagiersairbag MOET uitgeschakeld zijn!',
        examTipEn: 'Airbag rule: If mounting a rear-facing infant seat on the front passenger seat, the front airbag MUST be turned off!',
      },
    ],
  },
  {
    id: 'eindterm-4',
    eindtermNumber: 4,
    title: 'Verantwoorde, veilige en professionele verkeersdeelname',
    titleEn: 'Safe & Professional Driving Behavior',
    titleAr: 'القيادة المسؤولة والآمنة والاحترافية',
    subtitle: 'Defensief rijden, alcohol- en medicijnnormen, telefoonverbod en reactietijd',
    subtitleEn: 'Defensive driving, alcohol/medicine limits, phone bans and stopping distances',
    subtitleAr: 'القيادة الدفاعية، حدود الكحول والأدوية، حظر الهاتف ومسافة التوقف',
    icon: 'Shield',
    domain: 'gedrag',
    pageRange: 'p. 53 – 55',
    subsections: [
      {
        id: '4-1-defensief-rijden',
        heading: 'Anticiperen & Defensieve Rijstijl',
        headingEn: 'Anticipation & Defensive Driving',
        headingAr: 'التوقع المبكر وأسلوب القيادة الدفاعي',
        content: 'Als beroepschauffeur bent u een voorbeeld in het verkeer. Een defensieve rijstijl betekent dat u vooruitkijkt, rekening houdt met fouten van andere weggebruikers, en altijd voldoende volgafstand bewaart (minimaal 2 seconden regel, meer bij regen of gladheid). Professioneel rijden is rustig accelereren en tijdig uitrollen, wat zorgt voor comfort voor uw passagiers en brandstofbesparing.',
        contentEn: 'As a professional chauffeur, you set the benchmark for road safety. Defensive driving means looking ahead, anticipating mistakes by pedestrians and cyclists, and maintaining a 2-second buffer (expanded in poor weather). Smooth braking and early coasting ensure passenger comfort and lower fuel consumption.',
        contentAr: 'كسائق محترف، يجب أن تكون نموذجاً يحتذى به في الطريق. أسلوب القيادة الدفاعي يعني التطلع للأمام وتوقع أخطاء الآخرين مع الحفاظ على مسافة أمان كافية (قاعدة الثانيتين على الأقل، وتزيد في المطر والجليد) مع القيادة بسلاسة لراحة الركاب وتوفير الوقود.',
        keyPoints: [
          'Volgafstand: Minimaal 2 seconden onder normale omstandigheden.',
          'Stopafstand formule: Stopafstand = Reactieweg + Remweg.',
          'Spiegelafstelling: Binnenspiegel en beide buitenspiegels zo afstellen dat dode hoeken minimaal zijn.',
          'Anticiperen voorkomt plotseling remmen, wat essentieel is bij rolstoel- en ziekenvervoer.',
        ],
        keyPointsEn: [
          'Following distance: Minimum 2 seconds in good conditions.',
          'Stopping distance formula: Total Stopping Distance = Reaction Distance + Braking Distance.',
          'Mirror alignment: Interior and exterior mirrors adjusted to minimize blind spots.',
          'Anticipation prevents harsh braking, crucial for wheelchair and healthcare passengers.',
        ],
        examTip: 'Vergeet de formule niet: Stopafstand = Reactieafstand + Remafstand. Bij dubbele snelheid wordt de remafstand 4x zo lang!',
        examTipEn: 'Remember the physics: Doubling your speed quadruples your braking distance!',
      },
      {
        id: '4-2-alcohol-medicijnen',
        heading: 'Alcohol, Drugs, Medicijnen & Telefoon',
        headingEn: 'Alcohol, Substances, Medications & Phone Usage',
        headingAr: 'الكحول، المخدرات، الأدوية المحذرة واستخدام الهاتف',
        content: 'Voor beroepschauffeurs geldt de reguliere wettelijke alcohollimiet van maximaal 0,5 promille (220 µg/l), tenzij het een beginnend bestuurder betreft (eerste 5 jaar na rijbewijs B: maximaal 0,2 promille). Veel taxibedrijven hanteren een nultolerantie (0,0 promille). Medicijnen met een gele waarschuwingssticker beïnvloeden de rijvaardigheid en mogen niet worden gebruikt tijdens dienst. Het vasthouden van een mobiele telefoon tijdens het rijden is ten strengste verboden.',
        contentEn: 'For experienced professional taxi drivers, the legal blood alcohol limit is 0.5‰ (220 µg/l), whereas for novice drivers (first 5 years of license B) it is strictly 0.2‰. Most companies enforce a 0.0‰ zero-tolerance rule. Prescription medicines bearing a yellow warning sticker impair reaction time and cannot be used while driving. Holding any mobile phone is strictly outlawed.',
        contentAr: 'الحد القانوني للكحول للسائق المتمرس هو 0.5 في الألف (220 ميكروغرام/لتر)، بينما للسائق المبتدئ (أول 5 سنوات) هو 0.2 فقط، وتفرض معظم الشركات 0.0 خالية تماماً. الأدوية ذات الملصق التحذيري الأصفر تؤثر على التركيز ويحظر القيادة تحت تأثيرها. كما يُمنع تماماً حمل الهاتف باليد أثناء القيادة.',
        keyPoints: [
          'Ervaren bestuurder: Maximaal 0,5 promille bloedalcohol (220 µg/l uitgeademde lucht).',
          'Beginnend bestuurder (< 5 jaar rijbewijs): Maximaal 0,2 promille (88 µg/l).',
          'Medicijnen met gele sticker: Rijvaardigheid beïnvloed, verboden achter het stuur.',
          'Mobiele telefoon: Nooit in de hand houden tijdens het rijden (ook niet bij stilstaan in de file of voor een rood licht)!',
        ],
        keyPointsEn: [
          'Experienced drivers: Legal ceiling is 0.5‰ blood alcohol (220 µg/l breath).',
          'Novice drivers (< 5 years license): Maximum 0.2‰ (88 µg/l breath).',
          'Yellow sticker meds: Negatively impact driving faculties; do not drive.',
          'Mobile phone: Strictly prohibited in hand while moving or stationary in active traffic (traffic lights/jams).',
        ],
        examTip: 'Vraag over mobiele telefoon: Mag je de telefoon in de hand houden als je stilstaat voor een rood verkeerslicht? Antwoord: NEE, ook dan ben je verkeersdeelnemer!',
        examTipEn: 'Exam trap: Can you hold your phone while stopped at a red light? Answer: NO, you are still actively participating in traffic!',
      },
    ],
  },
  {
    id: 'eindterm-5',
    eindtermNumber: 5,
    title: 'Optreden bij verkeersongevallen, verstoringen en calamiteiten',
    titleEn: 'Accidents, Emergencies & Breakdown Procedures',
    titleAr: 'التعامل مع حوادث الطرق والأعطال وحالات الطوارئ',
    subtitle: 'PAMAN-methode, 112 alarmeren, Europees schadeformulier en pech langs de snelweg',
    subtitleEn: 'PAMAN protocol, calling 112, European claim form and highway breakdown safety',
    subtitleAr: 'بروتوكول PAMAN، الاتصال بالطوارئ 112، نموذج الحوادث وسلامة العطل على السريع',
    icon: 'AlertTriangle',
    domain: 'paman',
    pageRange: 'p. 56 – 60',
    subsections: [
      {
        id: '5-1-paman-methode',
        heading: 'De PAMAN-methode bij Ongevallen',
        headingEn: 'The PAMAN Emergency Response Protocol',
        headingAr: 'بروتوكول PAMAN للتعامل مع الحوادث والإسعاف',
        content: 'Bij een verkeersongeval handelt de taxichauffeur altijd volgens de vaste stappen van PAMAN: P = Persoonlijke veiligheid eerst (veiligheidshesje aan, veilige opstelplek); A = Anderen beschermen (passagiers in veiligheid brengen achter de vangrail); M = Markeren van de ongevalslocatie (gevarendriehoek op 30m op 50km/u wegen of 100m op snelwegen, alarmlichten aan); A = Alarmeren van hulpdiensten via 112; N = Noodzakelijke eerste hulp verlenen.',
        contentEn: 'When encountering or involved in an accident, follow the proven PAMAN sequence: P = Personal safety first (high-vis vest, safe exit); A = Protect others (move passengers behind safety barrier); M = Mark the hazard (hazard lights, warning triangle 30m in town / 100m on highway); A = Alert 112 dispatch; N = Necessary first aid.',
        contentAr: 'عند وقوع حادث يجب على السائق اتباع خطوات PAMAN بالترتيب: P = السلامة الشخصية أولاً (ارتداء السترة العاكسة)؛ A = حماية الآخرين بنقلهم خلف الحاجز الفولاذي؛ M = تمييز مكان الحادث بمثلث الخطر (30م في المدينة و100م على السريع)؛ A = الاتصال بالطوارئ 112؛ N = تقديم الإسعافات الأولية الضرورية.',
        keyPoints: [
          'P = Persoonlijke veiligheid (veiligheidshesje aandoen vóór uitstappen).',
          'A = Anderen beschermen (passagiers achter de vangrail laten wachten).',
          'M = Markeren ongeval (alarmlichten, gevarendriehoek plaatsen).',
          'A = Alarmeren hulpdiensten (112 bellen: wie, wat, waar, hoeveel gewonden).',
          'N = Noodzakelijke eerste hulp verlenen (reanimatie, bloedingen stelpen, slachtoffer warm houden).',
        ],
        keyPointsEn: [
          'P = Personal safety (slip on high-visibility vest before stepping out).',
          'A = Protect others (guide passengers behind highway crash barrier).',
          'M = Mark incident (hazard lights, triangle 30m local / 100m highway).',
          'A = Alert emergency services (call 112 with exact hectometer marker, casualties).',
          'N = Necessary first aid (bleeding, CPR, shock prevention).',
        ],
        examTip: 'CBR volgorde-vraag: Wat doe je als allereerste bij een ongeval? Altijd je eigen PERSOONLIJKE VEILIGHEID waarborgen (P)!',
        examTipEn: 'First priority question: What is step 1 at an accident scene? ALWAYS Personal safety (P)!',
      },
      {
        id: '5-2-schadeformulier-pech',
        heading: 'Europees Schadeformulier & Pech op de Snelweg',
        headingEn: 'European Accident Statement & Highway Breakdowns',
        headingAr: 'نموذج الحوادث الأوروبي وتدابير الأعطال على الطريق السريع',
        content: 'Bij blikschade zonder gewonden vullen beide partijen het Europees Schadeformulier in. Beide bestuurders vullen de voorzijde gezamenlijk in, kruisen de situatievakjes aan, maken een situatieschets en zetten hun handtekening. Erken NOOIT aansprakelijkheid of schuld op het formulier! De achterzijde vult u thuis zelfstandig in voor uw eigen verzekeraar. Bij pech op de snelweg: stuur direct naar de vluchtstrook, wielen naar rechts draaien, passagiers aan de rechterkant uitstappen en achter de vangrail wachten met hesjes.',
        contentEn: 'For property-only collisions, both drivers complete the front of the European Claim Form together (diagram, ticked boxes, signatures). NEVER admit guilt or liability on this document! The reverse side is completed privately at home for your insurer. During highway breakdowns: steer to the hard shoulder, turn wheels right toward embankment, exit via right doors, and wait behind the guardrail wearing vests.',
        contentAr: 'في الحوادث التي تقتصر على أضرار مادية، يقوم الطرفان بتعبئة الوجه الأمامي لنموذج الحوادث معاً وتوقيعه. إياك والاعتراف بالذنب أو المسؤولية على النموذج! الوجه الخلفي يُملأ لاحقاً في المنزل لشركة التأمين. عند العطل على السريع: توجه لكتف الطريق، أدر المقود لليمين، واخرجوا من الأبواب اليمنى وانتظروا خلف الحاجز مع السترات العاكسة.',
        keyPoints: [
          'Voorzijde schadeformulier: Gezamenlijk invullen en beide partijen ondertekenen.',
          'Schuldvraag: Nooit schuld bekennen op het schadeformulier!',
          'Achterzijde schadeformulier: Thuis rustig invullen voor de eigen verzekering.',
          'Pech op de snelweg: Alarmlichten aan, wielen rechts gedraaid, achter de vangrail wachten.',
          'Vervangend vervoer regelen voor de passagier via de centrale.',
        ],
        keyPointsEn: [
          'Front page: Completed jointly, signed by both drivers.',
          'Liability: NEVER admit guilt or fault on the form.',
          'Back page: Filled out individually later for your insurer.',
          'Motorway breakdown: Hazard lights on, wheels pointed right, wait behind guardrail.',
          'Arrange alternative ride for your passengers via taxi dispatch.',
        ],
        examTip: 'Examentruc: "Mag u op het schadeformulier schrijven dat het uw schuld was?" Antwoord: NEE, de verzekeraars bepalen wie de schuldige is!',
        examTipEn: 'Classic exam trap: "Should you write on the claim form that you caused the accident?" Answer: NO, insurers determine legal fault!',
      },
    ],
  },
  {
    id: 'eindterm-6',
    eindtermNumber: 6,
    title: 'Communicatie',
    titleEn: 'Professional Communication',
    titleAr: 'مهارات التواصل الاحترافي',
    subtitle: 'Beroepshouding, LSD-techniek, BCT-communicatie met de centrale en de-escalatie',
    subtitleEn: 'Chauffeur etiquette, LSD listening method, BCT dispatch messages and de-escalation',
    subtitleAr: 'سلوك المهنة، تقنية LSD للاستماع، مراسلات BCT مع الشركة وتهدئة التوتر',
    icon: 'MessageSquare',
    domain: 'gedrag',
    pageRange: 'p. 61',
    subsections: [
      {
        id: '6-1-gesprekstechnieken',
        heading: 'Beroepshouding & LSD-methode',
        headingEn: 'Professional Demeanour & LSD Communication Method',
        headingAr: 'المظهر المهني وتقنية LSD في التواصل',
        content: 'Als taxichauffeur bent u het visitekaartje van het bedrijf. Een verzorgd uiterlijk, vriendelijke begroeting en behulpzaamheid (portier openen, koffers inladen) maken het verschil. Bij communicatie gebruikt u de LSD-techniek: Luisteren (laat de klant uitpraten zonder te onderbreken), Samenvatten (herhaal in eigen woorden wat de klant bedoelt) en Doorvragen (vraag door als iets onduidelijk is over adres of wensen).',
        contentEn: 'As a taxi driver, you are the brand ambassador of your company. Neat attire, courteous greetings, and helpful service (opening doors, lifting luggage) define quality. Practice the Dutch LSD communication technique: Luisteren (listen actively without interrupting), Samenvatten (summarize in your own words), and Doorvragen (ask follow-up questions to clarify destination or special needs).',
        contentAr: 'السائق هو واجهة الشركة. المظهر الأنيق والتحية اللطيفة والمساعدة (فتح الباب وحمل الحقائب) تصنع الفارق. استخدم تقنية LSD في الحديث: L (الاستماع دون مقاطعة)، S (التلخيص بكلماتك للتأكد من الفهم)، وD (طرح أسئلة توضيحية عن العنوان أو الاحتياجات).',
        keyPoints: [
          'LSD = Luisteren, Samenvatten, Doorvragen.',
          'Altijd actief luisteren: oogcontact maken en de klant laten uitspreken.',
          'Non-verbale communicatie: open lichaamshouding, glimlach en rustige stem.',
          'Privacy respecteren: luister niet mee met privégesprekken van klanten.',
        ],
        keyPointsEn: [
          'LSD = Luisteren (Listen), Samenvatten (Summarize), Doorvragen (Deepen/Clarify).',
          'Active listening: eye contact, nodding, never interrupting an upset customer.',
          'Body language: relaxed posture, reassuring vocal tone.',
          'Client confidentiality: do not eavesdrop or discuss private passenger matters.',
        ],
        examTip: 'CBR vraagt vaak naar de LSD-methode: Wat betekent de S in LSD? Samenvatten!',
        examTipEn: 'Frequent question: What does the S stand for in the LSD method? Samenvatten (Summarizing)!',
      },
      {
        id: '6-2-centrale-communicatie',
        heading: 'Communicatie met de Centrale & BCT',
        headingEn: 'Dispatch Communication & BCT Status Codes',
        headingAr: 'التواصل مع مركز العمليات وحالات جهاز BCT',
        content: 'De communicatie met de centrale verloopt primair via de Boordcomputer Taxi (BCT) of mobiele dataterminal met statusknoppen (bijv. "Onderweg naar klant", "Klant ingestapt", "Bestemming bereikt", "Leeg terug"). Bij calamiteiten, vertraging door files of een no-show (klant niet aanwezig op adres na minimaal 5-10 minuten wachten) meldt u dit direct volgens de bedrijfsprocedure aan de centrale.',
        contentEn: 'Communication with dispatch is primarily handled via BCT data buttons ("En route", "Passenger aboard", "At destination", "Empty return"). For heavy traffic delays or no-show passengers (waiting at least 5-10 minutes past pickup time), drivers must report promptly according to internal protocols.',
        contentAr: 'يتم التواصل مع مركز التوزيع غالباً عبر شاشة BCT وأزرار الحالة (في الطريق للعميل، ركب العميل، تم الوصول، عودة فارغ). في حال الاختناق المروري أو عدم حضور العميل (بعد انتظار 5-10 دقائق على الأقل)، يتم إبلاغ المركز فوراً.',
        keyPoints: [
          'Statusknoppen op BCT zorgen voor accurate ritadministratie.',
          'No-show procedure: Eerst bellen, wachttijd aanhouden, dan centrale inlichten.',
          'In geval van bedreiging/nood: discrete noodknop op de BCT gebruiken.',
        ],
        keyPointsEn: [
          'BCT status buttons ensure accurate digital record-keeping.',
          'No-show protocol: Attempt phone contact, observe grace period, then inform dispatch.',
          'Panic situation: Utilize silent BCT emergency alert button.',
        ],
        examTip: 'BCT noodknop zendt een stil alarm naar de meldkamer zonder dat de agressor het ziet of hoort!',
        examTipEn: 'The BCT panic button dispatches a silent distress alarm to the control room without alerting the passenger!',
      },
    ],
  },
  {
    id: 'eindterm-7',
    eindtermNumber: 7,
    title: 'Omgang met passagiers',
    titleEn: 'Passenger Care & Target Groups',
    titleAr: 'التعامل مع الركاب وفئات النقل المتخصصة',
    subtitle: 'Algemene voorwaarden, rolstoelvervoer ISO 10542, ziekenvervoer dialyse en leerlingenvervoer clusters',
    subtitleEn: 'General conditions, ISO 10542 wheelchair securing, dialysis transport and special ed school clusters',
    subtitleAr: 'الشروط العامة، تثبيت الكراسي المتحركة ISO 10542، نقل مرضى الغسيل ونقل طلاب التربية الخاصة',
    icon: 'Users',
    domain: 'gedrag',
    pageRange: 'p. 62 – 90',
    subsections: [
      {
        id: '7-1-algemene-voorwaarden',
        heading: 'Algemene Voorwaarden & Vervoersplicht',
        headingEn: 'General Terms of Carriage & Duty of Transport',
        headingAr: 'الشروط العامة للنقل وواجب نقل الركاب',
        content: 'Op de openbare taxistandplaats heeft de chauffeur in beginsel een vervoersplicht: u mag een rit niet weigeren omdat deze te kort is of omdat de klant wil pinnen. Uitzonderingen waarbij u WEL mag weigeren: de passagier is agressief, zwaar onder invloed van drank of drugs, dreigt het voertuig te vervuilen, of weigert te betalen. Bagage van redelijke omvang en blindengeleidehonden of officiële hulphonden moeten ALTIJD gratis worden meegenomen.',
        contentEn: 'At public taxi stands, drivers have an obligation of transport: you cannot decline a fare for being too short or because the customer wants to pay by debit card. Lawful grounds for refusal: aggressive or heavily intoxicated customers, risk of soiling the vehicle, or non-payment. Normal luggage and guide dogs must ALWAYS be accommodated at no extra charge.',
        contentAr: 'في مواقف التاكسي العامة، يلتزم السائق بواجب النقل: لا يجوز رفض أي رحلة لقصر مسافتها أو لرغبة الراكب في الدفع بالبطاقة البنكية. الحالات المسموح فيها بالرفض: الراكب المعتدي أو المخمور بشدة، أو من يهدد باتساخ السيارة، أو يرفض الدفع. الحقائب العادية وكلاب مساعدة المكفوفين تنقل مجاناً دائماً دون أي رسوم إضافية.',
        keyPoints: [
          'Korte rit weigeren op standplaats is STRENG VERBODEN.',
          'Blindengeleidehond en hulphond: Altijd gratis meenemen, ook bij allergie van chauffeur (zoek dan collegiale oplossing).',
          'Betaalmethoden: Chauffeur moet wisselgeld hebben en pin/creditcard accepteren.',
          'Gevonden voorwerpen: Binnen 24 uur melden/inleveren bij de taxionderneming of gemeente.',
        ],
        keyPointsEn: [
          'Refusing a short fare at a rank is STRICTLY PROHIBITED.',
          'Guide dogs / assistance dogs: Always carried free of charge.',
          'Payment methods: Driver must provide change and support electronic card payment.',
          'Lost property: Report and hand over within 24 hours to the operator or local municipality.',
        ],
        examTip: 'CBR strikvraag: "Mag u een blinde klant met een hulphond weigeren omdat u bang bent voor honden?" Antwoord: NEE, hulphonden mogen NOOIT geweigerd worden!',
        examTipEn: 'Classic CBR trap: "Can you refuse a passenger with a guide dog due to dog fear or allergies?" Answer: NO, guide dogs can never be refused!',
      },
      {
        id: '7-2-rolstoelvervoer',
        heading: 'Rolstoelvervoer & ISO 10542 Vastzetsysteem',
        headingEn: 'Wheelchair Transport & ISO 10542 Tie-Down System',
        headingAr: 'نقل الكراسي المتحركة ونظام التثبيت ISO 10542',
        content: 'Bij rolstoelvervoer staat veiligheid voorop. De rolstoel moet altijd in de rijrichting (voorwaarts) worden geplaatst en vastgezet met een gecertificeerd vierpunts-vastzetsysteem (ISO 10542). De passagier wordt vastgezet met een driepunts-veiligheidsgordel die aan het voertuig (de carrosserie) is bevestigd, NOOIT alleen aan de rolstoel zelf! Bij het rijden met een rolstoel over een stoeprand of helling rijdt u ALTIJD ACHTERUIT naar beneden om te voorkomen dat de passagier voorover valt.',
        contentEn: 'Wheelchair passengers must always face forwards in the driving direction and be secured with a certified 4-point tie-down system compliant with ISO 10542. The occupant must wear a dedicated 3-point seatbelt anchored to the vehicle chassis, never just the wheelchair belt. When descending curbs, ramps, or lifts, ALWAYS roll BACKWARDS to prevent the passenger tipping forward.',
        contentAr: 'في نقل الكراسي المتحركة، يوضع الكرسي دائماً باتجاه السير للأمام ويثبت بنظام تثبيت رباعي النقاط معتمد (ISO 10542). يربط الراكب بحزام أمان ثلاثي النقاط مثبت بهيكل السيارة وليس بالكرسي فقط! عند النزول عن رصيف أو منحدر، يُسحب الكرسي المتحرك للخلف دائماً (بالمقلوب) لمنع سقوط الراكب للأمام.',
        keyPoints: [
          'Rijrichting rolstoel: ALTIJD vooruit (in de rijrichting), nooit dwars of achteruit.',
          'Vastzetsysteem: Vierpuntsgordel volgens ISO 10542 norm.',
          'Persoonsgordel: Driepuntsgordel aan het voertuig verankerd (bekkengordel + schoudergordel).',
          'Stoeprand afdalen: ALTIJD achteruit naar beneden rijden.',
          'Remmen rolstoel: Altijd op de handrem zetten tijdens het vastzetten en tijdens de rit.',
        ],
        keyPointsEn: [
          'Wheelchair direction: ALWAYS facing forward, never sideways or backwards.',
          'Tie-down system: 4-point retractors compliant with ISO 10542.',
          'Occupant restraint: 3-point belt attached to vehicle body frame.',
          'Curb descent: ALWAYS pull wheelchair backwards down curbs and ramps.',
          'Wheelchair brakes: Apply parking brakes firmly while securing and in motion.',
        ],
        examTip: 'Examenvraag: "Hoe rijdt u een rolstoel van een stoeprand af?" Antwoord: ALTIJD ACHTERWAARTS (achteruit), zodat de passagier niet voorover uit de stoel kiept!',
        examTipEn: 'Key question: "How do you maneuver a wheelchair off a curb?" Answer: ALWAYS BACKWARDS, preventing the occupant from falling forward!',
      },
      {
        id: '7-3-ziekenvervoer',
        heading: 'Zittend Ziekenvervoer & Dialysepatiënten',
        headingEn: 'Healthcare Transport & Dialysis Patients',
        headingAr: 'نقل المرضى الجالسين ومرضى الغسيل الكلوي',
        content: 'Bij zittend ziekenvervoer vervoert u patiënten naar het ziekenhuis voor bestraling, chemotherapie of nierdialyse. Dialysepatiënten hebben na de behandeling vaak last van een "dialysekater" (extreme vermoeidheid, duizeligheid, misselijkheid en hoofdpijn). Rijd uiterst rustig en anticiperend. Let op de "shuntarm" van de patiënt: aan deze arm mag NOOIT een bloeddrukband, strakke kleding of zware belasting worden uitgeoefend.',
        contentEn: 'Healthcare taxi services transport patients undergoing chemotherapy, radiation, or kidney dialysis. Post-dialysis passengers frequently experience a "dialysis hangover" (severe fatigue, dizziness, nausea, low blood pressure). Drive exceptionally smoothly. Take note of the patient\'s shunt arm: this vascular access arm must never endure tight pressure, heavy bags, or strain.',
        contentAr: 'نقل المرضى يشمل نقل مصابي السرطان وجلسات الغسيل الكلوي. يعاني مريض الكلى بعد الجلسة من إرهاق شديد وهبوط وصداع (Dialysekater). قد بهدوء تام دون تسارع أو فرملة مفاجئة. انتبه ليد القسطرة (Shunt) للغسيل: لا يجوز شدها أو ضغطها بحزام أو حمل أكياس عليها.',
        keyPoints: [
          'Dialysekater: Passagier is misselijk, extreem moe en duizelig na dialyse.',
          'Rijstijl: Zeer defensief, rustig optrekken en remmen, drempels stapvoets nemen.',
          'Shunt: Kunstmatige aderverbinding in de arm; wees voorzichtig bij in- en uitstappen.',
          'Begeleiding: Vaak nodig tot in de wachtruimte of overdracht aan verpleging.',
        ],
        keyPointsEn: [
          'Dialysis hangover: Patient is dizzy, exhausted and nauseous post-treatment.',
          'Driving approach: Ultra-gentle acceleration and braking; crawl over speed bumps.',
          'Shunt arm: Surgical vascular bridge; handle with utmost delicacy during transfers.',
          'Escort duties: Guiding the passenger safely right to the clinic reception or ward.',
        ],
        examTip: 'Examenconcept "dialysekater": Dit is geen kater van alcohol, maar de fysieke uitputting en duizeligheid na het filteren van het bloed bij nierdialyse!',
        examTipEn: 'Exam concept "dialysekater": Not related to alcohol, but physical exhaustion caused by blood filtration during renal dialysis!',
      },
      {
        id: '7-4-leerlingenvervoer',
        heading: 'Leerlingenvervoer & Onderwijsclusters 1 t/m 4',
        headingEn: 'Pupil Transport & Special Education Clusters 1 to 4',
        headingAr: 'نقل الطلاب وتصنيفات مدارس التربية الخاصة 1 إلى 4',
        content: 'Leerlingenvervoer brengt kinderen naar het speciaal onderwijs. De overheid deelt dit in vier clusters in: Cluster 1 = Visuele beperking (blind of slechtziend); Cluster 2 = Auditieve beperking (doof, slechthorend) en taal-/spraakstoornissen; Cluster 3 = Verstandelijke en/of lichamelijke beperkingen en langdurig zieke kinderen; Cluster 4 = Gedragsstoornissen en psychiatrische problematiek (ADHD, ODD, Autisme/ASS). Bij leerlingenvervoer gelden strikte rugzakregels en duidelijke vaste zitplaatsen.',
        contentEn: 'Special educational needs (SEN) school transport is categorized into four state clusters: Cluster 1 = Visual impairments (blind/partially sighted); Cluster 2 = Auditory & communication disorders (deaf/hard of hearing/speech); Cluster 3 = Physical/intellectual disabilities & chronic illnesses; Cluster 4 = Behavioral disorders & psychiatric conditions (ADHD, ODD, Autism/ASD). Fixed seating and consistent routines are vital.',
        contentAr: 'نقل طلاب التعليم الخاص ينقسم إلى 4 مجموعات رسمية (Clusters): المجموعة 1 = إعاقات بصرية (كفيف/ضعيف بصر)؛ المجموعة 2 = إعاقات سمعية ونطقية؛ المجموعة 3 = إعاقات حركية وذهنية وأمراض مزمنة؛ المجموعة 4 = اضطرابات سلوكية ونفسية (ADHD، التوحد ASS). يلتزم السائق بروتين ثابت ومقاعد مخصصة لكل طالب.',
        keyPoints: [
          'Cluster 1: Visueel beperkt (blind en slechtziend).',
          'Cluster 2: Doof, slechthorend, spraak- en taalontwikkelingsstoornissen.',
          'Cluster 3: Lichamelijk en verstandelijk gehandicapt, meervoudig beperkt of langdurig ziek.',
          'Cluster 4: Psychiatrische aandoeningen en ernstige gedragsproblemen (ADHD, ASS/autisme).',
          'Vaste structuur: Vaste zitplaats, vaste chauffeur en vaste route bieden rust en voorkomen escalatie.',
        ],
        keyPointsEn: [
          'Cluster 1: Visually impaired (blind and low vision).',
          'Cluster 2: Deaf, hard of hearing, and speech-language processing disorders.',
          'Cluster 3: Physical & intellectual disabilities, or long-term chronic illness.',
          'Cluster 4: Behavioral disorders and psychiatric needs (ADHD, ASD, emotional disturbance).',
          'Routine & consistency: Predictable schedules, assigned seats, and calm demeanor prevent meltdowns.',
        ],
        examTip: 'CBR test de clusters regelmatig: Onthoud dat Cluster 4 gaat over GEDRAG en PSYCHIATRISCHE stoornissen (zoals ADHD en Autisme)!',
        examTipEn: 'Must-know CBR exam question: Cluster 4 covers BEHAVIORAL and PSYCHIATRIC disorders (ADHD, Autism)!',
      },
      {
        id: '7-5-beperkingen-adhd-autisme',
        heading: 'Omgang met Autisme (ASS) & ADHD',
        headingEn: 'Interacting with Autism (ASD) & ADHD',
        headingAr: 'التعامل مع اضطراب طيف التوحد (ASS) وفرط الحركة (ADHD)',
        content: 'Passagiers met Autisme Spectrum Stoornis (ASS) hebben grote behoefte aan voorspelbaarheid, rust en duidelijke instructies. Vermijd plotselinge routewijzigingen, luide radio of fel licht. Kondig veranderingen tijdig aan. Passagiers met ADHD zijn snel overprikkeld en impulsief; benader hen positief, geef korte en eenduidige instructies en vermijd ellenlange discussies over regels in de auto.',
        contentEn: 'Passengers with Autism Spectrum Disorder (ASD) depend on predictability, sensory calm, and clarity. Avoid impromptu route changes, loud music, or harsh cabin lights. Announce milestones ahead of time. Passengers with ADHD experience impulsivity and sensory overload; communicate using concise, positive language rather than endless scolding.',
        contentAr: 'ركاب طيف التوحد (ASS) يحتاجون بشدة إلى الهدوء والوضوح والروتين الثابت. تجنب تغيير مسار الرحلة فجأة وتجنب الموسيقى العالية أو الأضواء الساطعة، وأخبرهم مسبقاً بأي تغيير. ركاب فرط الحركة (ADHD) يتسمون بالاندفاع وتشتت الانتباه؛ تعامل معهم بإيجابية وتوجيهات قصيرة ومباشرة وتجنب الجدال.',
        keyPoints: [
          'Autisme (ASS): Houd vast aan routine; kondig elke verandering vooraf rustig aan.',
          'Prikkelarm vervoeren: Zet radio zacht, praat op rustige toon, vermijd felle verlichting.',
          'ADHD: Duidelijke, positieve grenzen stellen ("Blijf rustig zitten" i.p.v. "Niet bewegen").',
          'Dementie/Ouderen: Geduld tonen, rustig laten instappen en geruststellen bij verwarring.',
        ],
        keyPointsEn: [
          'Autism (ASD): Stick to routine; give advance notice of upcoming traffic delays.',
          'Low-stimulus environment: Lower radio volume, speak calmly, dim cabin glare.',
          'ADHD: Provide concise positive instructions ("Please keep your seatbelt flat").',
          'Dementia/Elderly: Patient assistance, gentle reassurance, escorting safely to doorstep.',
        ],
        examTip: 'Bij autisme: Altijd ruim van tevoren vertellen wat er gaat gebeuren. Nooit plotseling onverwachte handelingen verrichten!',
        examTipEn: 'Key tip for autism: Always explain upcoming steps in advance. Never surprise them with unannounced sudden changes!',
      },
    ],
  },
  {
    id: 'eindterm-8',
    eindtermNumber: 8,
    title: 'Conflictsituaties en agressie',
    titleEn: 'Conflict Management & Aggression',
    titleAr: 'إدارة النزاعات والتعامل مع العدوانية',
    subtitle: 'Vormen van agressie, de RAAK-methode en de-escalerend handelen',
    subtitleEn: 'Forms of aggression, RAAK de-escalation protocol and personal safety',
    subtitleAr: 'أنواع العدوانية، تقنية RAAK لتهدئة النزاع وسلامة السائق',
    icon: 'Flame',
    domain: 'gedrag',
    pageRange: 'p. 91 – 92',
    subsections: [
      {
        id: '8-1-vormen-agressie',
        heading: 'Vormen van Agressie & Oorzaken',
        headingEn: 'Forms & Drivers of Aggression',
        headingAr: 'أشكال العدوانية وأسبابها',
        content: 'In het taxivak onderscheiden we drie hoofdvormen van agressie: 1. Frustratie-agressie (emotioneel: de klant heeft een slechte dag, de taxi is te laat, uit zich in boosheid tegen de situatie); 2. Doelgerichte of instrumentele agressie (berekenend: de klant gebruikt intimidatie bewust om een korting of gratis rit af te dwingen); 3. Willekeurige agressie (vaak onder invloed van alcohol of drugs, onvoorspelbaar gedrag).',
        contentEn: 'Taxi professionals face three distinct classes of aggression: 1. Frustration aggression (emotional: passenger had a bad day or taxi arrived late, directed at circumstances); 2. Instrumental/goal-oriented aggression (calculated: using intimidation or bullying to extort a discount or evade payment); 3. Random/substance-fueled aggression (unpredictable behavior under alcohol/drugs).',
        contentAr: 'تنقسم العدوانية في عمل التاكسي إلى ثلاثة أصناف رئيسية: 1. عدوانية الإحباط (انفعالية بسبب تأخر التاكسي أو يوم سيء، موجهة للموقف)؛ 2. العدوانية الهادفة أو الاستغلالية (مدروسة واستفزازية لإجبار السائق على تخفيض السعر أو الركوب مجاناً)؛ 3. العدوانية العشوائية (غير متوقعة غالباً تحت تأثير المخدرات أو المسكرات).',
        keyPoints: [
          'Frustratie-agressie: Niet persoonlijk bedoeld; los je op door begrip te tonen en te luisteren.',
          'Doelgerichte agressie: Duidelijke grenzen stellen; de agressor wil je manipuleren.',
          'Agressie onder invloed: Veiligheid waarborgen, niet in discussie gaan, zo nodig rit beëindigen.',
        ],
        keyPointsEn: [
          'Frustration: Not personal; de-escalated via empathy, active listening and solutions.',
          'Instrumental: Set firm boundaries; the aggressor seeks calculated control.',
          'Substance-induced: Focus purely on safety; avoid debating, terminate trip if unsafe.',
        ],
        examTip: 'Belangrijk onderscheid: Bij frustratie-agressie toon je begrip; bij doelgerichte agressie stel je duidelijke grenzen!',
        examTipEn: 'Crucial exam distinction: With frustration you show understanding; with goal-oriented aggression you set firm limits!',
      },
      {
        id: '8-2-raak-methode',
        heading: 'De RAAK-methode bij Agressie',
        headingEn: 'The RAAK Aggression De-escalation Sequence',
        headingAr: 'تقنية RAAK لتهدئة وحسم المواقف العدوانية',
        content: 'Bij oplopende spanningen past u de beproefde RAAK-methode toe: R = Rustig blijven (ademhaling onder controle houden, rustige lage stem); A = Accepteren / Aandacht geven (luister naar het bezwaar, erken het gevoel); A = Afwegen / Aanbod doen (zoek een redelijke oplossing of bied een keuze); K = Keuze voorleggen of Klap ontwijken / Kappen (als het gedrag aanhoudt: duidelijke keuze stellen tussen normaal gedrag of direct stoppen van de rit).',
        contentEn: 'When confrontation escalates, execute the RAAK model: R = Remain calm (controlled breathing, slow low vocal tone); A = Acknowledge / Attend (validate the emotions without accepting abuse); A = Assess / Offer options (propose practical alternatives); K = Key choice / Knockout dodge / Quit trip (enforce a boundary: cooperate or exit vehicle).',
        contentAr: 'عند تصاعد التوتر نطبق خطوات RAAK: R = الهدوء وضبط النفس؛ A = الاستماع والاهتمام بالمشكلة؛ A = تقييم الموقف وتقديم عرض بديل؛ K = وضع الخيار الحاسم أمام الراكب (إما الالتزام أو إنهاء الرحلة ومغادرة التاكسي فوراً لحماية نفسك).',
        keyPoints: [
          'R = Rustig blijven (ademhaling, lichaamstaal onder controle).',
          'A = Accepteren van emotie en Aandacht tonen voor de klacht.',
          'A = Afwegen en Aanbod doen (constructieve oplossing voorstellen).',
          'K = Keuze voorleggen of Kappen (duidelijke grens stellen: meewerken of uitstappen).',
          'Bij fysiek geweld: Nooit vechten, auto stoppen op verlichte plek, vluchten en 112 bellen.',
        ],
        keyPointsEn: [
          'R = Rustig blijven (Remain calm in voice and demeanor).',
          'A = Accepteren (Acknowledge emotions and show genuine attention).',
          'A = Afwegen & Aanbod (Assess options and offer workable solutions).',
          'K = Keuze & Kappen (Present clear choice or terminate the contract).',
          'In physical danger: Pull over in a well-lit populated area, escape and summon 112.',
        ],
        examTip: 'CBR vraagt: "Waar staat de letter R in de RAAK-methode voor?" Antwoord: Rustig blijven!',
        examTipEn: 'Frequent question: What does the first R stand for in the RAAK method? Rustig blijven (Remain calm)!',
      },
    ],
  },
  {
    id: 'eindterm-9',
    eindtermNumber: 9,
    title: 'Klachtenprocedure',
    titleEn: 'Complaints Procedure',
    titleAr: 'إجراءات معالجة الشكاوى والنزاعات',
    subtitle: 'Interne klachtenafhandeling, Geschillencommissie Taxivervoer en registratie',
    subtitleEn: 'Internal complaint handling, Taxi Transport Disputes Committee and recording',
    subtitleAr: 'المعالجة الداخلية للشكاوى، لجنة فض منازعات التاكسي وتوثيق البلاغات',
    icon: 'FileCheck',
    domain: 'gedrag',
    pageRange: 'p. 93',
    subsections: [
      {
        id: '9-1-klachtenafhandeling',
        heading: 'Klachtenregeling & Geschillencommissie',
        headingEn: 'Complaints Handling & Disputes Committee',
        headingAr: 'نظام الشكاوى ولجنة فض النزاعات الرسمية',
        content: 'Elk taxibedrijf is wettelijk verplicht een duidelijke en toegankelijke interne klachtenregeling te hebben. Een ontevreden klant dient zijn klacht eerst in bij het taxibedrijf. Het bedrijf moet de klacht binnen een redelijke termijn (meestal binnen 4 tot 6 weken) onderzoeken en schriftelijk beantwoorden. Komt men er samen niet uit, dan kan de klant zich wenden tot de onafhankelijke Geschillencommissie Taxivervoer (onderdeel van De Geschillencommissie in Den Haag). De uitspraak van deze commissie is bindend voor beide partijen.',
        contentEn: 'Every taxi enterprise is required by law to maintain an accessible dispute procedure. Dissatisfied passengers first submit their grievance to the carrier. The carrier must investigate and respond within 4 to 6 weeks. If unresolved, the passenger may escalate to the independent Taxi Transport Disputes Committee in The Hague, whose binding arbitration ruling is final for both parties.',
        contentAr: 'كل شركة تاكسي ملزمة قانوناً بوجود إجراءات واضحة لمعالجة الشكاوى. يقدم العميل شكواه أولاً للشركة، وعليها الرد خطياً خلال 4 إلى 6 أسابيع. في حال تعذر الحل الودي، يمكن للعميل اللجوء إلى لجنة منازعات التاكسي المستقلة (Geschillencommissie Taxivervoer)، وقرار هذه اللجنة ملزم ونهائي للطرفين.',
        keyPoints: [
          'Eerste stap: Klacht altijd eerst indienen bij het betrokken taxibedrijf.',
          'Reactietermijn: Binnen redelijke termijn (standaard 4-6 weken).',
          'Vervolgstap: Geschillencommissie Taxivervoer (Den Haag).',
          'Bindend advies: De uitspraak van de Geschillencommissie is juridisch bindend.',
          'Klachtenregistratie: Bedrijven moeten alle klachten en de afhandeling schriftelijk bewaren voor controle door ILT en SFM.',
        ],
        keyPointsEn: [
          'First step: Passenger submits grievance directly to the taxi operator.',
          'Response timeframe: Reasonable window (typically 4-6 weeks).',
          'Escalation: Independent Taxi Disputes Committee (De Geschillencommissie).',
          'Binding arbitration: The committee ruling has binding legal authority.',
          'Record retention: Operators must log all grievances and resolutions for ILT/SFM audits.',
        ],
        examTip: 'Examentruc: Kan een klant meteen naar de Geschillencommissie stappen? NEE, de klant moet de klacht altijd eerst bij het taxibedrijf zelf hebben ingediend!',
        examTipEn: 'Key exam rule: A passenger must ALWAYS attempt resolution with the taxi company first before the Disputes Committee will hear the case!',
      },
    ],
  },
  {
    id: 'eindterm-10',
    eindtermNumber: 10,
    title: 'Geografisch inzicht Nederland',
    titleEn: 'Geography & Dutch Road Network',
    titleAr: 'الجغرافيا وشبكة الطرق السريعة في هولندا',
    subtitle: 'Rijkswegen A1 t/m A29, 12 provincies met hoofdsteden, vaarwegen en luchthavens',
    subtitleEn: 'Motorways A1 to A29, 12 Dutch provinces and capitals, waterways and hubs',
    subtitleAr: 'الطرق السريعة الرئيسية A1 إلى A29، المقاطعات الـ12 وعواصمها والمطارات',
    icon: 'MapPin',
    domain: 'transport',
    pageRange: 'p. 94 – 95',
    subsections: [
      {
        id: '10-1-rijkswegennet',
        heading: 'Belangrijkste Snelwegen (A-wegen)',
        headingEn: 'Core Motorway Corridors (A-roads)',
        headingAr: 'أهم الطرق السريعة (محاور شبكة A)',
        content: 'Op het CBR-examen wordt uw geografische kennis van het Nederlandse rijkswegennet getoetst. De belangrijkste snelwegen die u uit het hoofd moet kennen: A1: Amsterdam – Amersfoort – Apeldoorn – Hengelo – De Lutte (Duitse grens); A2: Amsterdam – Utrecht – \'s-Hertogenbosch – Eindhoven – Maastricht (Belgische grens); A4: Amsterdam – Schiphol – Leiden – Den Haag – Rotterdam – Bergen op Zoom – Antwerpen; A10: Ringweg Amsterdam; A12: Den Haag – Gouda – Utrecht – Arnhem – Zevenaar (Duitse grens / Oberhausen); A15: Maasvlakte / Rotterdam Haven – Gorinchem – Tiel – Nijmegen/Bemmel; A16: Rotterdam – Dordrecht – Breda – Hazeldonk (België); A27: Breda – Utrecht – Hilversum – Almere; A28: Utrecht – Amersfoort – Zwolle – Assen – Groningen.',
        contentEn: 'CBR exams test core knowledge of the national highway grid: A1: Amsterdam to German border (De Lutte); A2: Amsterdam via Utrecht and Eindhoven to Maastricht / Belgium; A4: Amsterdam via Schiphol, The Hague and Rotterdam to Antwerp; A10: Amsterdam Ring; A12: The Hague via Utrecht and Arnhem to Oberhausen (Germany); A15: Rotterdam Port via Tiel to Nijmegen; A16: Rotterdam via Breda to Hazeldonk (Belgium); A27: Breda via Utrecht to Almere; A28: Utrecht via Zwolle to Groningen.',
        contentAr: 'يمتحن CBR معرفتك بشبكة الطرق السريعة الهولندية: A1 من أمستردام عبر أبلدورن إلى الحدود الألمانية؛ A2 من أمستردام عبر أوترخت وآيندهوفن إلى ماستريخت؛ A4 من أمستردام ومطار سخيبول عبر لاهاي وروتردام إلى أنتويرب؛ A10 حزام أمستردام الدائري؛ A12 من لاهاي عبر أوترخت وأرنهيم إلى الحدود الألمانية؛ A15 من ميناء روتردام عبر نايميخن؛ A16 من روتردام وبريدا إلى بلجيكا؛ A28 من أوترخت إلى خرونينغن.',
        keyPoints: [
          'A1: Amsterdam – Hilversum – Amersfoort – Apeldoorn – Deventer – Hengelo – Duitse grens.',
          'A2: Amsterdam – Utrecht – \'s-Hertogenbosch – Eindhoven – Weert – Maastricht.',
          'A4: Amsterdam – Schiphol – Den Haag – Rotterdam – Antwerpen.',
          'A12: Den Haag – Utrecht – Arnhem – Duitse grens (Oberhausen).',
          'A15: Rotterdam Havens – Gorinchem – Tiel – Nijmegen.',
          'A28: Utrecht – Amersfoort – Harderwijk – Zwolle – Assen – Groningen.',
        ],
        keyPointsEn: [
          'A1: Amsterdam – Amersfoort – Apeldoorn – Hengelo – Germany.',
          'A2: Amsterdam – Utrecht – \'s-Hertogenbosch – Eindhoven – Maastricht.',
          'A4: Amsterdam – Schiphol – The Hague – Rotterdam – Antwerp.',
          'A12: The Hague – Utrecht – Arnhem – Germany.',
          'A15: Port of Rotterdam – Gorinchem – Tiel – Nijmegen.',
          'A28: Utrecht – Zwolle – Assen – Groningen.',
        ],
        examTip: 'CBR vraagt vaak: "Welke snelweg verbindt Amsterdam via Utrecht met Maastricht?" Antwoord: De A2!',
        examTipEn: 'Frequent question: "Which motorway connects Amsterdam via Utrecht to Maastricht?" Answer: The A2!',
      },
      {
        id: '10-2-provincies-en-hoofdsteden',
        heading: 'De 12 Provincies & Hoofdsteden',
        headingEn: 'The 12 Dutch Provinces & Capital Cities',
        headingAr: 'المقاطعات الـ12 وعواصمها الإدارية',
        content: 'U moet alle twaalf provincies van Nederland en hun hoofdsteden kennen voor het theorie-examen: Noord-Holland (Haarlem), Zuid-Holland (Den Haag), Utrecht (Utrecht), Flevoland (Lelystad), Gelderland (Arnhem), Noord-Brabant (\'s-Hertogenbosch), Limburg (Maastricht), Zeeland (Middelburg), Overijssel (Zwolle), Drenthe (Assen), Groningen (Groningen), en Friesland (Leeuwarden). Belangrijke luchthavens: Schiphol (bij Amsterdam/Haarlemmermeer), Rotterdam The Hague Airport (Zestienhoven) en Eindhoven Airport.',
        contentEn: 'You must know all 12 provinces and capitals: Noord-Holland (Haarlem), Zuid-Holland (The Hague), Utrecht (Utrecht), Flevoland (Lelystad), Gelderland (Arnhem), Noord-Brabant (\'s-Hertogenbosch), Limburg (Maastricht), Zeeland (Middelburg), Overijssel (Zwolle), Drenthe (Assen), Groningen (Groningen), Friesland (Leeuwarden). Key hubs: Amsterdam Schiphol, Rotterdam The Hague, and Eindhoven Airport.',
        contentAr: 'يجب حفظ مقاطعات هولندا الـ12 وعواصمها للامتحان: شمال هولندا (هارلم)، جنوب هولندا (لاهاي)، أوترخت (أوترخت)، فليفولاند (ليليستاد)، خيلدرلاند (أرنهيم)، شمال برابانت (سيرتوخنبوس)، ليمبورغ (ماستريخت)، زيلاند (ميدلبورغ)، أوفريسل (زووله)، درينته (آسن)، خرونينغن (خرونينغن)، وفريزلاند (ليوفاردن). المطارات الرئيسية: سخيبول، روتردام لاهاي، ومطار آيندهوفن.',
        keyPoints: [
          'Noord-Holland hoofdstad: HAARLEM (niet Amsterdam!).',
          'Zuid-Holland hoofdstad: DEN HAAG (niet Rotterdam!).',
          'Noord-Brabant hoofdstad: \'S-HERTOGENBOSCH / DEN BOSCH (niet Eindhoven!).',
          'Flevoland hoofdstad: LELYSTAD (niet Almere!).',
          'Zeeland hoofdstad: MIDDELBURG (niet Vlissingen!).',
          'Luchthavens: Schiphol (A4/A9), Rotterdam Airport (A13), Eindhoven (A2).',
        ],
        keyPointsEn: [
          'Noord-Holland capital: HAARLEM (not Amsterdam!).',
          'Zuid-Holland capital: THE HAGUE (not Rotterdam!).',
          'Noord-Brabant capital: \'S-HERTOGENBOSCH (not Eindhoven!).',
          'Flevoland capital: LELYSTAD (not Almere!).',
          'Zeeland capital: MIDDELBURG (not Vlissingen!).',
          'Major airports: Schiphol (A4/A9), Rotterdam Airport (A13), Eindhoven (A2).',
        ],
        examTip: 'Klassieke CBR valkuilen: De hoofdstad van Noord-Holland is HAARLEM (niet Amsterdam!), en van Zuid-Holland DEN HAAG (niet Rotterdam)!',
        examTipEn: 'Classic trap: Capital of Noord-Holland is HAARLEM (not Amsterdam), and Zuid-Holland is THE HAGUE (not Rotterdam)!',
      },
    ],
  },
];

export const GLOSSARY_TERMS = [
  {
    term: 'Anticiperen',
    termEn: 'Anticipation',
    definition: 'Een situatie tijdig herkennen en vooruitkijken; stilstaan bij een verkeerssituatie en tijdig handelen om gevaar te voorkomen.',
    definitionEn: 'Early hazard perception and foresight; acting ahead of time to eliminate risk.',
  },
  {
    term: 'Beladen rit',
    termEn: 'Laden trip',
    definition: 'Een taxirit waarbij één of meerdere betalende passagiers in het voertuig aanwezig zijn.',
    definitionEn: 'A taxi trip with one or more fare-paying passengers on board.',
  },
  {
    term: 'Onbeladen rit',
    termEn: 'Unladen trip / empty run',
    definition: 'Een rit zonder passagiers, bijvoorbeeld onderweg naar een klant ("Voorrijden") of terug naar de standplaats/garage ("Leeg terug").',
    definitionEn: 'A trip without passengers, such as heading to a pickup or returning to garage.',
  },
  {
    term: 'Dialysekater',
    termEn: 'Dialysis hangover',
    definition: 'Fysieke vermoeidheid, duizeligheid, hoofdpijn en misselijkheid die een patiënt ervaart direct na een nierdialysebehandeling.',
    definitionEn: 'Severe fatigue, dizziness, and nausea experienced by patients directly following kidney dialysis.',
  },
  {
    term: 'Shuntarm',
    termEn: 'Shunt arm',
    definition: 'De arm waarin operatief een vaattoegang (shunt) is aangelegd voor nierdialyse; mag nooit bekneld of zwaar belast worden.',
    definitionEn: 'The arm with a surgically created vascular shunt for dialysis; must never undergo blood pressure cuffs or strain.',
  },
  {
    term: 'ISO 10542',
    termEn: 'ISO 10542 Standard',
    definition: 'De officiële internationale veiligheidsnorm voor het vierpunts-vastzetsysteem van rolstoelen en de bijbehorende driepunts-veiligheidsgordel.',
    definitionEn: 'International technical standard for 4-point wheelchair tie-downs and 3-point occupant restraints.',
  },
  {
    term: 'RAAK-methode',
    termEn: 'RAAK Method',
    definition: 'De vier stappen bij het de-escaleren van agressie: Rustig blijven, Accepteren/Aandacht, Afwegen/Aanbod, Keuze voorleggen of Kappen.',
    definitionEn: 'The 4-step aggression de-escalation protocol: Remain calm, Acknowledge, Assess/offer options, Key choice or terminate.',
  },
  {
    term: 'PAMAN',
    termEn: 'PAMAN Emergency Code',
    definition: 'De vaste volgorde van handelen bij een verkeersongeval: Persoonlijke veiligheid, Anderen beschermen, Markeren, Alarmeren (112), Noodzakelijke eerste hulp.',
    definitionEn: 'Accident response sequence: Personal safety, Protect others, Mark scene, Alert 112, Necessary first aid.',
  },
  {
    term: 'TTO',
    termEn: 'Authorized Taxi Organization',
    definition: 'Toegelaten Taxi Organisatie: een samenwerkingsverband van taxichauffeurs dat door de gemeente is erkend om op standplaatsen te staan.',
    definitionEn: 'Recognized taxi association required for operating on public taxi ranks in designated cities.',
  },
  {
    term: 'Geschillencommissie Taxivervoer',
    termEn: 'Taxi Disputes Committee',
    definition: 'Onafhankelijke instantie in Den Haag die bindende uitspraken doet over geschillen tussen reiziger en taxionderneming als zij er samen niet uitkomen.',
    definitionEn: 'Independent national arbitration body issuing binding rulings on passenger complaints that fail internal resolution.',
  },
];
